name: dmcgb
channels:
  - defaults
dependencies:
  - python=3.7.6
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - pip
  - pip:
    - numpy==1.19.5
    - pillow==6.2.0
    - termcolor==1.1.0
    - imageio
    - imageio-ffmpeg
    - opencv-python
    - xmltodict
    - tqdm
    - einops==0.4.1
    - kornia==0.6.4
    - glfw==1.12.0
